boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('list_themes', views.list_themes, name='list_themes'),
    path('create_theme', views.create_theme, name='create_theme'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
    path('save_comment', views.save_comment, name='save_comment'),
]

easy_bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

handler404 = show_error_page

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boards/models.py
from django.db import models


class ThemesManager(models.Manager):

    def fetch_all_themes(self):
        return self.order_by('id').all()


class Themes(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(
        'accounts.Users',
        on_delete=models.CASCADE,
    )

    objects = ThemesManager()

    class Meta:
        db_table = 'themes'


class CommentsManager(models.Manager):
    def fetch_by_theme_id(self, theme_id):
        return self.filter(theme_id=theme_id).order_by('id').all()


class Comments(models.Model):
    comment = models.CharField(max_length=1000)
    user = models.ForeignKey(
        'accounts.Users',
        on_delete=models.CASCADE,
    )
    theme = models.ForeignKey(
        'Themes',
        on_delete=models.CASCADE,
    )

    objects = CommentsManager()

    class Meta:
        db_table = 'comments'

boards/forms.py
from django import forms
from .models import Themes, Comments


class CreateThemeForm(forms.ModelForm):
    title = forms.CharField(label='Title')

    class Meta:
        model = Themes
        fields = ('title',)


class EditThemeForm(forms.ModelForm):
    title = forms.CharField(label='Title')

    class Meta:
        model = Themes
        fields = ('title',)


class DeleteThemeForm(forms.ModelForm):

    class Meta:
        model = Themes
        fields = []


class PostCommentForm(forms.ModelForm):
    comment = forms.CharField(label='', widget=forms.Textarea(attrs={'rows': 5, 'cols': 60}))

    class Meta:
        model = Comments
        fields = ('comment',)

boards/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from . import forms
from .models import Themes, Comments
from django.core.cache import cache
from django.http import JsonResponse


def create_theme(request):
    create_theme_form = forms.CreateThemeForm(request.POST or None)
    if create_theme_form.is_valid():
        # ログイン中のユーザを設定
        create_theme_form.instance.user = request.user

        create_theme_form.save()
        messages.success(request, '掲示板を作成しました。')
        return redirect('boards:list_themes')

    return render(request, 'boards/create_theme.html', context={
        'create_theme_form': create_theme_form,
    })


def list_themes(request):
    themes = Themes.objects.fetch_all_themes()
    return render(
        request,
        'boards/list_themes.html',
        context={
            'themes': themes,
        }
    )


def edit_theme(request, id):
    theme = get_object_or_404(Themes, id=id)

    # 作成者とログインユーザが異なる場合は404エラーを起こす
    if theme.user.id != request.user.id:
        raise Http404
    edit_theme_form = forms.EditThemeForm(request.POST or None, instance=theme)

    if edit_theme_form.is_valid():
        edit_theme_form.save()
        messages.success(request, '掲示板を更新しました')
        return redirect('boards:list_themes')

    return render(
        request,
        'boards/edit_theme.html',
        context={
            'edit_theme_form': edit_theme_form,
            'id': id,
        }
    )


def delete_theme(request, id):
    theme = get_object_or_404(Themes, id=id)

    if theme.user.id != request.user.id:
        raise Http404
    delete_theme_form = forms.DeleteThemeForm(request.POST or None)

    if delete_theme_form.is_valid():  # csrf_token check
        theme.delete()
        messages.success(request, '掲示板を削除しました')
        return redirect('boards:list_themes')

    return render(
        request,
        'boards/delete_theme.html',
        context={
            'delete_theme_form': delete_theme_form,
        }
    )


def post_comments(request, theme_id):
    # キャッシュから値を取り出す
    saved_comment = cache.get(f'saved_comment-theme_id={theme_id}-user_id={request.user.id}', '')

    post_comment_form = forms.PostCommentForm(request.POST or None, initial={'comment': saved_comment})
    theme = get_object_or_404(Themes, id=theme_id)
    comments = Comments.objects.fetch_by_theme_id(theme_id)

    if post_comment_form.is_valid():
        # 認証していないユーザーの場合エラーを返す
        if not request.user.is_authenticated:
            raise Http404

        # Commentsインスタンスのthemeフィールドにquery_param(theme_id)から取得したThemeインスタンスをセット
        post_comment_form.instance.theme = theme
        # 同様にログインユーザをセット
        post_comment_form.instance.user = request.user
        post_comment_form.save()

        # キャッシュから値を削除
        cache.delete(f'saved_comment-theme_id={theme_id}-user_id={request.user.id}')

        return redirect('boards:post_comments', theme_id=theme_id)

    return render(
        request,
        'boards/post_comments.html',
        context={
            'post_comment_form': post_comment_form,
            'theme': theme,
            'comments': comments,
        }
    )


# Ajaxを利用して、Commentを一時的に保存する
def save_comment(request):
    if request.is_ajax():
        comment = request.GET.get("comment")
        theme_id = request.GET.get('theme_id')
        if comment and theme_id:
            # メモリキャッシュに一時的に保存する
            cache.set(f'saved_comment-theme_id={theme_id}-user_id={request.user.id}', comment)

            # JSONとして返す
            return JsonResponse({
                'message': '一時保存しました。'
            })

templates/boards/create_theme.html
{% extends 'base.html' %}
{% block content %}
	<h2>Create board page</h2>
	<hr />
	<form method="post">
		{% csrf_token %}
		{{ create_theme_form.as_p }}
		<input class="btn btn-primary" type="submit" value="Create" />
	</form>
{% endblock %}

templates/boards/delete_theme.html
{% extends 'base.html' %}
{% block content %}
	<h3>Are you sure to delete?</h3>
	<hr />
	<form method="post">
		{% csrf_token %}
		{{ delete_theme_form.as_p }}
		<input class="btn btn-danger" type="submit" value="Delete" />
	</form>
{% endblock %}

templates/boards/edit_theme.html
{% extends 'base.html' %}
{% block content %}
	<h2>Edit board page</h2>
	<hr />
	<form method="post">
		{% csrf_token %}
		{{ edit_theme_form.as_p }}
		<div class="inline">
			<input class="btn btn-primary" type="submit" value="Edit" />
			<a href="{% url 'boards:delete_theme' id=id %}" class="btn btn-outline-danger">Delete</a>
		</div>
	</form>
{% endblock %}

templates/boards/list_themes.html
{% extends 'base.html' %}
{% block content %}
	{% if messages %}
		{% for message in messages %}
			<div>{{ message.message }}</div>
		{% endfor %}
	{% endif %}
	<h2>Board lists page</h2>
	<hr />
	<p>
		<a class="navbar-brand" href="{% url 'boards:create_theme' %}">
			Create
		</a>
	</p>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Title</th>
				<th>User</th>
			</tr>
		</thead>
		<tbody>
			{% for theme in themes %}
				<tr>
					<td>{{ forloop.counter }}</td>
					<td><a href="{% url 'boards:post_comments' theme_id=theme.id %}">{{ theme.title }}</a></td>
					{% if theme.user.id == user.id %}
						<td>
							<a href="{% url 'boards:edit_theme' id=theme.id %}">
								{{ theme.user }}
							</a>
						</td>
					{% else %}
						<td>
						{{ theme.user }}
						</td>
					{% endif %}
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/boards/post_comments.html
{% extends 'base.html' %}
{% block content %}
	<h2>{{ theme.title }}</h2>
	<hr />

	{% for comment in comments %}
		<div class="col-1 offset-1">
			{% if comment.user.picture %}
			<img style="float: left;" src="{{ comment.user.picture.url }}" alt="comment user picture" width="50px" height="50px" />
			{% endif %}
		</div>
		<div class="col-8 offset-2">
			<p>Name: {{ comment.user.username }}</p>
			<p>{{ comment.comment | linebreaks }}</p>
		</div>
		<div class="col-10 offset-1">
			<hr />
		</div>
	{% endfor %}

	{% if user.is_authenticated %}
		<div class="col-4 offset-7">
			<form method="post">
				{% csrf_token %}
				{{ post_comment_form.as_p }}
				<input id="save_comment" class="btn btn-warning" type="button" value="Temporarily saved" />
				<input class="btn btn-primary" type="submit" value="Post" />
			</form>
		</div>
	{% endif %}
{% endblock %}

{% block javascript %}
	<script>
		$("#save_comment").click(() => {
			let comment = $("#id_comment").val()

			// コメントを一時保存するためのAjaxを定義
			$.ajax({
				url: "{% url 'boards:save_comment' %}",
				type: 'GET',
				data: {comment: comment, theme_id: "{{ theme.id }}"},
				dataType: "json",
				success: (json) => {
					if (json.message) {
						alert(json.message)
					}
				}
			})
		})
	</script>
{% endblock %}