accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('edit', views.user_edit, name='edit'),
    path('change_password', views.change_password, name='change_password'),
    path('activate/<uuid:token>', views.activate_user, name='activate'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('list_themes', views.list_themes, name='list_themes'),
    path('create_theme', views.create_theme, name='create_theme'),
    path('edit_theme/<int:id>', views.edit_theme, name='edit_theme'),
    path('delete_theme/<int:id>', views.delete_theme, name='delete_theme'),
    path('post_comments/<int:theme_id>', views.post_comments, name='post_comments'),
    path('save_comment', views.save_comment, name='save_comment'),
]

easy_bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import show_error_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

handler404 = show_error_page

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8" />
		<!-- Bootstrap5 @see https://getbootstrap.jp/docs/5.0/getting-started/introduction/ -->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
			crossorigin="anonymous"
		>
		<!-- jQuery CDN for Ajax @see https://code.jquery.com/ -->
		<script
			src="https://code.jquery.com/jquery-3.6.0.js"
			integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
			crossorigin="anonymous"></script>
		<title>Easy Bulletin Board</title>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light mx-3">
			<a class="navbar-brand" href="{% url 'accounts:home' %}">
				Home
			</a>
			<a class="navbar-brand" href="{% url 'boards:list_themes' %}">
				Themes
			</a>
			{% if user.is_authenticated %}
				<a class="navbar-brand" href="{% url 'accounts:logout' %}">
					Logout
				</a>
				<a class="navbar-brand" href="{% url 'accounts:edit' %}">
					Profile
				</a>
			{% else %}
				<a class="navbar-brand" href="{% url 'accounts:register' %}">
					Register
				</a>
				<a class="navbar-brand" href="{% url 'accounts:login' %}">
					Login
				</a>
			{% endif %}
		</nav>
		<div class="container pt-2">
			{% block content %}{% endblock %}
		</div>
		{% block javascript %}{% endblock %}
	</body>
</html>